### ISSUE TITLE
cliar requires Python >=3.6,<4.0

### ISSUE THREAD

**Issue by AdrienPensart** [moigagoo/cliar#16]
Hello !

very well thought project!

I had a little glitch when adding to my project : 

```
poetry add cliar
Using version ^1.3.4 for cliar

Updating dependencies
Resolving dependencies... (0.5s)

[SolverProblemError]
The current project's Python requirement (>=3.6) is not compatible with some of the required packages Python requirement:
  - cliar requires Python >=3.6,<4.0

Because cliar (1.3.4) requires Python >=3.6,<4.0
 and no versions of cliar match >1.3.4,<2.0.0, cliar is forbidden.
So, because run-cli-unity depends on cliar (^1.3.4), version solving failed.
```

I had to modify in my pyproject.toml : 

[tool.poetry.dependencies]
python = ">=3.6,<4.0"

Do you know why <4.0 is needed ?
Thank you!

**Comment by moigagoo** [comment]
@AdrienPensart sorry for the slow response. Apparently, I was not "watching" my own repos, so I didn't get any notification about this issue 😒

I don't think I put this constraint manually, it was probably generated by Poetry during package setup. Also, there is no <4.0 part in pyproject.toml for Cliar, so the error message is super weird 🤔

https://github.com/moigagoo/cliar/blob/develop/pyproject.toml#L14

Maybe, it's a Poetry issue? Are you using the latest version? Also, what Python version are you using?

**Comment by moigagoo** [comment]
@AdrienPensart Oh, I think I get it! This constraint `python = "^3.6"` is equivalent to `python = ">=3.6,<4.0"`. You should probably use the former in your project instead of the latter, since its the say Poetry generates pyproject.toml files by default.

**Comment by AdrienPensart** [comment]
That's ok for me ! Thank you!
